# Generated by Django 4.0.2 on 2022-02-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
